name: CI

on:
  push:
    branches:
      - master

jobs:
  infer:
    name: Static analysis (Infer)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master branch
      uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Install 42sh dependencies
      run: |
        sudo apt install -y libncurses5-dev
    - name: Install Infer
      env:
        VERSION: "0.17.0"
      run: |
        wget "https://github.com/facebook/infer/releases/download/v${VERSION}/infer-linux64-v${VERSION}.tar.xz"
        tar xJf "infer-linux64-v${VERSION}.tar.xz"
        rm -rf "infer-linux64-v${VERSION}.tar.xz"
    - name: Generate compilation database
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 ..
    - name: Run Infer
      env:
        VERSION: "0.17.0"
      run: |
        export LD_LIBRARY_PATH="$(realpath infer-linux64-v${VERSION}/lib/infer/infer/libso)"
        cd build
        ../infer-linux64-v${VERSION}/bin/infer --compilation-database compile_commands.json run
        ../infer-linux64-v${VERSION}/bin/infer --compilation-database compile_commands.json explore --html
    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export COMMIT_HASH="$(echo "${GITHUB_SHA}" | cut -c1-7)"
        cd build/infer-out/report.html
        git config --global user.email ''
        git config --global user.name 'GitHub Actions'
        git init
        git remote add origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}"
        git add --all
        git commit -m "Generated reports for ${COMMIT_HASH}"
        git branch gh-pages
        git checkout gh-pages
        git push -uf origin gh-pages
